base_url = "https://semanticdata.github.io/zola-minimal/"
title = "Minimal"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum neque eget nunc mattis eu sollicitudin enim tincidunt."

compile_sass = true
build_search_index = false
generate_feed = false
minify_html = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
highlight_code = false
highlight_theme = "ayu-light"

[extra]
logo = "/img/logo.png"
sidebar = [
  { name = "Links", urls = [
    { name = "Posts", url = "posts/" },
    { name = "Firefox", url = "posts/unlock-firefox-sidebar/" },
    { name = "Tags", url = "tags/" },
    { name = "#placeholder", url = "tags/placeholder/" },
  ] },
]
