# Site's URL. Please include trailing "/".
base_url = "https://semanticdata.github.io/zola-minimal/"
title = "Minimal"
description = "Minimal is a Zola theme based on the Jekyll theme of the same name."

compile_sass = true
build_search_index = false
generate_feed = false
minify_html = false

[markdown]
highlight_code = true
