name = "Minimal"
description = "ðŸ“š Minimal is a Zola port of the Jekyll theme with the same name."
license = "MIT"
homepage = "https://github.com/semanticdata/zola-minimal/"
min_version = "0.18.0"
demo = "https://miguelpimentel.do/zola-minimal/"

[extra]

[author]
name = "Miguel Pimentel"
homepage = "https://miguelpimentel.do/"

[original]
author = "pages-themes"
homepage = "https://pages-themes.github.io/minimal/"
repo = "https://github.com/pages-themes/minimal"
